#!/bin/bash
# mkosi PostInstallationScript, run inside mkosi's sandbox. mkosi 27 mounts
# the image tree at $BUILDROOT — the sandbox's own / is read-only staging —
# so every mutation of the image happens through a chroot into it. The chroot
# needs /proc, /sys and /dev mounted (mkinitcpio hard-fails without /proc:
# "==> ERROR: /proc must be mounted!").
# Installs the factory identity: the savant account, enabled units, host
# identity, and the factory initramfs.
set -euo pipefail

echo "[finalize] savantos factory image configuration (BUILDROOT=$BUILDROOT)"
[[ -d $BUILDROOT/etc ]] || { echo "finalize: BUILDROOT not mounted" >&2; exit 1; }

# The configuration payload as a script INSIDE the tree, so it runs the same
# way regardless of which chroot mechanism executes it (no stdin threading).
# Not under /tmp: the sandbox tmpfs-mounts /tmp, hiding anything planted
# there from the chroot (proved empirically 2026-09-12).
payload=/usr/local/lib/savantos/finalize-payload.sh
cat > "$BUILDROOT$payload" <<'CHROOT'
set -eux

# Skeletons arrive via mkosi SkeletonTrees=skeletons:/ (copied into the image
# tree before packages install); fix the exec bits the copy normalizes away.
chmod 755 /usr/local/lib/savantos/guest-ready /usr/local/lib/savantos/request-sshd

# --- factory account (F6): single desktop user, passwordless sudo for the
# dev/admin path until the desktop phase brings the real policy.
if ! id savant >/dev/null 2>&1; then
    useradd -m -G wheel -s /bin/bash savant
fi
printf 'savant:savant\n' | chpasswd
printf '%%wheel ALL=(ALL:ALL) NOPASSWD: ALL\n' > /etc/sudoers.d/90-savant-wheel
chmod 440 /etc/sudoers.d/90-savant-wheel

# --- autologin on tty1 so the boot proof shows a usable console without a
# display manager (the desktop phase adds SDDM).
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf <<'UNIT'
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-f savant' --noclear --autologin savant %I $TERM
UNIT

# --- hostname + hosts
printf 'savantos\n' > /etc/hostname
cat > /etc/hosts <<'HOSTS'
127.0.0.1 localhost
::1 localhost
HOSTS

# --- locale (C is honest for Phase 1; the desktop phase carries the host
# locale sync from the integration set)
printf 'LANG=C.UTF-8\n' > /etc/locale.conf

# --- deterministic UTC clock at first boot. systemd-firstboot is disabled
# on the kernel command line (systemd.firstboot=0), but /etc/localtime must
# still exist: without it the RTC stays UTC and the firstboot timezone
# question was the Phase 1 boot blocker (interactive prompt on the serial
# console, hanging sysinit.target before sshd). The Phase 2 host-locale
# service replaces this with the Windows zone per boot.
ln -sfn /usr/share/zoneinfo/UTC /etc/localtime

# --- unit enablement is NOT done with hand-made wants symlinks: mkosi runs
# `systemctl preset-all` AFTER this script and strips them (observed
# 2026-09-12). Enablement is declared in the factory preset policy
# (skeletons/usr/lib/systemd/system-preset/90-savantos-factory.preset),
# which preset-all applies; the growfs-root [Install] comes from its drop-in.

# --- sshd host keys: NOT generated at build — random keys per build broke
# the dual-build determinism gate. The sshd unit's ExecStartPre generates
# them at first boot (idempotent), where /etc rides the launcher's
# persistent data disk and survives updates.

# --- /etc/shadow determinism: chpasswd hashes with a random salt per build
# (gate breaker). Set the hash directly with a FIXED salt instead (dev
# password 'savant'; the production hardening pass replaces this).
savant_hash=$(openssl passwd -6 -salt savantosfixedsalt 'savant')
usermod -p "$savant_hash" savant

# --- factory initramfs with the virtio-only drop-in
mkinitcpio -p linux-zen

# --- the build metadata lives at a stable path for the emitter and for
# in-guest inspection
mkdir -p /usr/share/savantos
printf 'phase1\n' > /usr/share/savantos/image-stream

# --- nondeterminism hygiene: caches regenerated by the guest at boot.
# ldconfig aux-cache varies with build-time filesystem ordering; the boot
# ldconfig rebuilds it. /etc/shadow- is shadow's automatic backup, holding
# the pre-usermod random-salt hash; the fixed-salt hash above is the last
# account mutation, then the backup is refreshed to match.
# NOTE: mkosi's kernel-modules initrd (/boot/arch) is created AFTER this
# script runs, so it cannot be removed here — assemble.sh removes it.
rm -f /var/cache/ldconfig/aux-cache
rm -f /etc/shadow-
cp /etc/shadow /etc/shadow-
CHROOT
chmod 755 "$BUILDROOT$payload"

# Chroot with the API VFS mounted. mkosi-chroot is mkosi's own helper: it
# chroots into the image tree by itself (BUILDROOT is baked into it) and runs
# the given command inside. Probed empirically rather than assumed; if it is
# absent or refuses, fall back to manual mounts in a private user+mount
# namespace.
if mkosi-chroot /bin/true >/dev/null 2>&1; then
    echo "[finalize] chroot via mkosi-chroot"
    mkosi-chroot /bin/bash "$payload"
else
    echo "[finalize] mkosi-chroot unusable; unshare fallback"
    unshare --user --map-root-user --mount /bin/bash -eux <<FALLBACK
mount -t proc proc '$BUILDROOT/proc'
mount --rbind /sys '$BUILDROOT/sys'
mount --rbind /dev '$BUILDROOT/dev'
chroot '$BUILDROOT' /bin/bash '$payload'
umount -R '$BUILDROOT/dev' '$BUILDROOT/sys' '$BUILDROOT/proc'
FALLBACK
fi

rm -f "$BUILDROOT$payload"
echo "[finalize] done"
